[package]
name = "bandoripet-native"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
name = "bandoripet"
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21.1", default-features = false }
libloading = "0.8.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = "symbols"

